#!/usr/bin/env python3
"""
galaxy_places.py — the shared placement layer for the feed fleet.

Every wire in the fleet answers the same question about a story: where is this
happening. This resolves it in five passes, stopping at the first that answers:

  1  a settlement named in the text            Kharkiv, Kaohsiung, Cuiabá
  2  a first-level division                    Bavaria, Kerala, Xinjiang, Ohio
  3  a country, by name or by demonym          Nigeria, Nigerian, Nigeria's
  4  an institution that belongs to one         EFSA, Ofcom, ANVISA, Pentagon
  5  the country the source itself reports from

Pass 5 is the weakest claim, so it is marked: a point placed that way carries
approx=True and the page draws it hollow, because "the Japanese wire ran this"
is not the same knowledge as "this happened in Osaka".

Ambiguity is handled by guarding, not by deleting. A term whose lowercase form
is also an everyday word carries guard=1 and matches only where the headline
capitalises it, so "Turkey bans the platform" places and "how to brine a
turkey" does not. Names a title-case headline would capitalise anyway — a
surname, or a word as common as the place — are absent from the table.

Because the guard reads capitalisation, callers must pass the story text as it
was written. Passing text that has already been lowercased still works; it
simply forfeits every guarded term.

Generated by build_gazetteer2.py. Do not hand-edit the table.
"""

import gzip
import json
import os
import re

_HERE = os.path.dirname(os.path.abspath(__file__))
_DATA = os.path.join(_HERE, "places.json.gz")

with gzip.open(_DATA, "rt", encoding="utf-8") as _fh:
    _RAW = json.load(_fh)

# term -> [label, lat, lon, rank, guard, cc]
#   rank  3 settlement, 2 division, 1 country
#   guard 1 means the term must appear capitalised to count
#   cc    the ISO-2 the place belongs to, so a wire can file the story under
#         its own region taxonomy without guessing from the coordinates
TABLE = _RAW["table"]
# ISO-2 of a Google News locale -> the point to fall back on
LOCALE = _RAW["locale"]
# an institution's name -> the ISO-2 it belongs to
INSTITUTIONS = _RAW["institutions"]
# a currency or legal marker -> the ISO-2 it belongs to
MARKERS = _RAW.get("markers", {})

_WORD = re.compile(r"\w", re.UNICODE)
_CJK = re.compile(r"[\u3040-\u30ff\u3400-\u9fff\uac00-\ud7af]")
# scripts written without spaces between words, where a word-boundary test
# would reject every correct match
_NOBREAK = re.compile(r"[\u0e00-\u0e7f\u1780-\u17ff\u0f00-\u0fff"
                      r"\u3040-\u30ff\u3400-\u9fff\uac00-\ud7af]")
_TOKEN = re.compile(r"[^\W\d_]+", re.UNICODE)
_UPPER = re.compile(r"[A-Z\u00c0-\u00de\u0100-\u024f\u0386-\u03ab\u0400-\u042f]")

_INFLECTED = re.compile(r"[\u0370-\u03ff\u0400-\u04ff]")   # Greek, Cyrillic
_INFLECT_MAX = 3          # "Новосибирск" + "е", "Украин" + "ою"


def _fold(text):
    """Lowercase without changing the string's length.

    str.lower() is not length-preserving for every character — Turkish 'İ'
    lowercases to two code points — and the guard has to look up the original
    character at a matched offset, so the two strings must stay in step.
    """
    out = []
    for ch in text:
        low = ch.lower()
        out.append(low if len(low) == 1 else ch)
    return "".join(out)


def _edges(text, term, start):
    """Word-boundary test, adapted to the scripts the fleet actually reads.

    Chinese and Japanese are written without word breaks, so a boundary test
    would reject every correct match; for those terms position alone is the
    test. Greek and Russian inflect the place name itself — a story says "в
    Новосибирске", not "в Новосибирск" — so a short trailing ending is allowed
    there. Everywhere else the character on either side must not be a word
    character, or "mali" matches inside "Somalia"."""
    if _NOBREAK.search(term):
        return True
    if start > 0 and _WORD.match(text[start - 1]) and _WORD.match(term[0]):
        return False
    end = start + len(term)
    if end >= len(text) or not _WORD.match(text[end]):
        return True
    if not _INFLECTED.search(term):
        return False
    tail = 0
    while end + tail < len(text) and _WORD.match(text[end + tail]):
        tail += 1
        if tail > _INFLECT_MAX:
            return False
    return True


def _find(text, term):
    i = text.find(term)
    while i >= 0:
        if _edges(text, term, i):
            return i
        i = text.find(term, i + 1)
    return -1


# --------------------------------------------------------------------------
# Index. Scanning seventy-odd thousand terms against every headline is far too
# slow for a harvest, so terms are filed under their first word and only the
# words a headline actually contains are ever looked up. Terms in scripts with
# no word breaks cannot be indexed that way and are scanned directly, but there
# are few enough of those for it not to matter.
# --------------------------------------------------------------------------
_BY_FIRST = {}
_SCAN = []

for _term, _entry in TABLE.items():
    if _CJK.search(_term):
        _SCAN.append((_term, _entry))
        continue
    _head = _TOKEN.search(_term)
    if not _head:
        _SCAN.append((_term, _entry))
        continue
    _BY_FIRST.setdefault(_head.group(0), []).append((_term, _entry))

# longest first inside each bucket, so "south sudan" is tested before "sudan"
for _k in _BY_FIRST:
    _BY_FIRST[_k].sort(key=lambda kv: -len(kv[0]))
_SCAN.sort(key=lambda kv: -len(kv[0]))


def _guard_ok(raw, pos):
    """Whether a guarded term is capitalised where it was matched."""
    if pos >= len(raw):
        return False
    ch = raw[pos]
    if not ch.isalpha():
        return True
    return bool(_UPPER.match(ch)) or ch.isupper()


def _scan(text):
    """The best (rank, -position, label, lat, lon) the text offers, or None.

    text is the story as written. Matching runs against a length-preserving
    lowercase of it so that a guarded term can still read the original case at
    the offset where it matched.

    Matches are collected with their spans and any match lying inside a longer
    one is discarded before the winner is chosen. Without that step a more
    specific rank always won on containment: "North Carolina" is a division and
    "Carolina" a settlement in Puerto Rico, so every North Carolina story
    pinned in San Juan.
    """
    low = _fold(text)
    found = []

    for m in _TOKEN.finditer(low):
        word = m.group(0)
        bucket = _BY_FIRST.get(word)
        if bucket is None and _INFLECTED.search(word):
            # the name itself carries the case ending, so the token in the text
            # is longer than the term filed in the index
            for cut in range(1, _INFLECT_MAX + 1):
                if len(word) - cut < 4:
                    break
                bucket = _BY_FIRST.get(word[:-cut])
                if bucket:
                    break
        if not bucket:
            continue
        for term, entry in bucket:
            if not low.startswith(term, m.start()):
                continue
            if not _edges(low, term, m.start()):
                continue
            if entry[4] and not _guard_ok(text, m.start()):
                # a guarded term that is not capitalised here; a shorter term
                # starting at the same word may still be a legitimate match,
                # so keep looking rather than giving up on the position
                continue
            found.append((m.start(), len(term), entry))
            break          # longest surviving match at this position wins

    if _CJK.search(low):
        for term, entry in _SCAN:
            pos = _find(low, term)
            if pos >= 0:
                found.append((pos, len(term), entry))
                if entry[3] == 3:
                    break

    if not found:
        return None

    kept = []
    for pos, length, entry in found:
        inside = any(p <= pos and pos + length <= p + l and l > length
                     for p, l, _e in found)
        if not inside:
            kept.append((entry[3], -pos, entry[0], entry[1], entry[2],
                         entry[5] if len(entry) > 5 else None))
    if not kept:
        return None
    return max(kept)


def _from_tables(text):
    """An institution or a currency marker standing in for its jurisdiction."""
    low = _fold(text)
    hit = None
    for name, iso in INSTITUTIONS.items():
        if iso not in LOCALE:
            continue
        pos = _find(low, name)
        if pos >= 0 and (hit is None or len(name) > len(hit[0])):
            hit = (name, iso)
    if hit:
        return hit[1]
    for marker, iso in MARKERS.items():
        if iso in LOCALE and marker in text:
            return iso
    return None


def resolve_ranked(text, locale=None):
    """Where the story is, and how specific the answer is.

    Returns (label, [lat, lon], rank, approx) where rank is 3 a settlement,
    2 a division, 1 a country or institution, 0 the reporting locale, and -1
    nothing. approx is True only for the reporting-locale case.

    Pass the text as written; lowercasing it first forfeits guarded terms.
    """
    label, point, rank, approx, _cc = resolve_full(text, locale)
    return label, point, rank, approx


def resolve_full(text, locale=None):
    """As resolve_ranked, and also the ISO-2 the answer belongs to.

    The country code is what lets a wire file the story under its own region
    taxonomy. Without it a wire that placed a story from the gazetteer still
    counted it as unlocated, so the pin appeared on the map and the story
    vanished the moment anyone touched the region filter.
    """
    best = _scan(text or "")
    if best:
        return best[2], [best[3], best[4]], best[0], False, best[5]

    iso = _from_tables(text or "")
    if iso:
        pt = LOCALE[iso]
        return pt[0], [pt[1], pt[2]], 1, False, iso

    if locale:
        code = str(locale).upper()
        pt = LOCALE.get(code)
        if pt:
            return pt[0], [pt[1], pt[2]], 0, True, code

    return None, None, -1, False, None


def resolve(text, locale=None):
    """As resolve_ranked, without the rank: (label, [lat, lon], approx)."""
    label, point, _rank, approx = resolve_ranked(text, locale)
    return label, point, approx


def resolve_point(text, locale=None):
    """The two-value form the harvesters' point_for() already returns."""
    label, point, _approx = resolve(text, locale)
    return label, point
